[project]
name = "eng-prompt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "colorama>=0.4.6",
    "dotenv>=0.9.9",
    "groq>=0.20.0",
    "pyperclip>=1.9.0",
    "streamlit>=1.44.0",
]
